name: test
on:
  push:
    branches: ['main', 'feature/**', 'renovate/**', 'githubPage/**']

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # "GitHub Action for npx" is only supported [macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: GitHub Action for npx
        uses: mikeal/npx@v2.0.0

      # 2023/10/7 一時的に無効化
      # - id: prettier-check
      #   run: npx prettier --check .
      #   shell: bash

      # for debug
      # - name: Extract branch name
      #   shell: bash
      #   run: |
      #     echo ${GITHUB_REF}
      #     echo ${GITHUB_REF#refs/heads/}
      #     echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      #   id: extract_branch

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: echo $BRANCH_NAME

  for-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # for debug
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version:
          # for debug
          # ['2.7', '3.7', '3.8', '3.9', '3.10', 'pypy2.7', 'pypy3.8']
          ['3.10']
        # for debug
        # exclude:
        #   - os: macos-latest
        #     python-version: '3.8'
        #   - os: windows-latest
        #     python-version: '3.6'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Python
        uses: actions/setup-python@v5
        # for debug
        # with:
        #   python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
